// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLEWxA_BxaQFMbNy4QlrugRaSGgw7mxc',
    appId: '1:616242790288:android:be4b453c498bf3c4087d15',
    messagingSenderId: '616242790288',
    projectId: 'sosite-7f912',
    storageBucket: 'sosite-7f912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcZhGEJq7684Ik-5xyGPr00SEfZsRQzA',
    appId: '1:616242790288:ios:39ee554ff3248ac6087d15',
    messagingSenderId: '616242790288',
    projectId: 'sosite-7f912',
    storageBucket: 'sosite-7f912.appspot.com',
    androidClientId: '616242790288-rghdh9f1ertdrak2bmu2bo6hlf7ilep0.apps.googleusercontent.com',
    iosClientId: '616242790288-lscgbsd00e6sef1ugum9hn0mfoiqcpij.apps.googleusercontent.com',
    iosBundleId: 'com.toic.sosite',
  );
}
